export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILED = "LOGIN_FAILED"

export const LOGOUT = "LOGOUT";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const ADMIN_CREATE_USER = "ADMIN_CREATE_USER";
export const ADMIN_CREATE_USER_SUCCESS = "ADMIN_CREATE_USER_SUCCESS";
export const ADMIN_CREATE_USER_FAILED = "ADMIN_CREATE_USER_FAILED";

export const REQUEST_READ_FEED = "REQUEST_READ_FEED";
export const SUCCESS_READ_FEED = "SUCCESS_READ_FEED";
export const FAILED_READ_FEED = "FAILED_READ_FEED";

export const REQUEST_CREATE_ARTICLE = 'REQUEST_CREATE_ARTICLE';
export const SUCCESS_CREATE_ARTICLE = "SUCCESS_CREATE_ARTICLE";
export const FAILED_CREATE_ARTICLE= "FAILED_CREATE_ARTICLE";

export const REQUEST_READ_ARTICLE = 'REQUEST_READ_ARTICLE';
export const SUCCESS_READ_ARTICLE = "SUCCESS_READ_ARTICLE";
export const FAILED_READ_ARTICLE = "FAILED_READ_ARTICLE";

export const REQUEST_CREATE_GIF = 'REQUEST_CREATE_GIF';
export const SUCCESS_CREATE_GIF = "SUCCESS_CREATE_GIF";
export const FAILED_CREATE_GIF = "FAILED_CREATE_GIF";

export const REQUEST_GIF = 'REQUEST_GIF';
export const REQUEST_GIF_SUCCESS = "REQUEST_GIF_SUCCESS";
export const REQUEST_GIF_FAILED = "REQUEST_GIF_FAILED";

export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION";
